import Link from "next/link"
import { Button } from "@/components/ui/button"
import { SectionChip, SectionHeading, HonestyNote, StatPill } from "@/components/explainer"

/* Incentives, explained — the three directions value can flow, the guardrails
   that bound every trigger, and one worked example with real numbers. */

const DIRECTIONS = [
  {
    tag: "Harmful — by A or by B",
    tone: "risk" as const,
    flow: "aggressor's pool → harmed side's pool",
    body: "When a harmful event is proven — a cross-border attack, a rights violation — a capped slice of the responsible community's staked pool moves to the harmed community's pool. The cost lands only on capital that side opted in, and the harmed side's members claim it as an equal dividend. Symmetric by construction: A's aggression costs A exactly what B's aggression costs B.",
    viz: (
      <div className="flex items-center justify-center gap-2 text-xs font-bold">
        <span className="rounded-lg bg-amber-500/20 px-2 py-1.5 text-amber-700 dark:text-amber-300">pool X −slice</span>
        <span className="text-primary">→</span>
        <span className="rounded-lg bg-primary/15 px-2 py-1.5 text-primary">pool Y +dividend</span>
      </div>
    ),
  },
  {
    tag: "Positive — for A or for B",
    tone: "positive" as const,
    flow: "shared Treasury → acting side's pool",
    body: "When one side takes a proven de-escalation step — removing a checkpoint, withdrawing troops — the reward comes from the shared Treasury (funded by outsider premiums and donations), never from the other community. Rewarding one side's peace work by taxing the other would manufacture grievance instead of dissolving it; the code makes that impossible.",
    viz: (
      <div className="flex items-center justify-center gap-2 text-xs font-bold">
        <span className="rounded-lg bg-accent/70 px-2 py-1.5 text-accent-foreground">Treasury −reward</span>
        <span className="text-primary">→</span>
        <span className="rounded-lg bg-primary/15 px-2 py-1.5 text-primary">acting pool +dividend</span>
      </div>
    ),
  },
  {
    tag: "Joint",
    tone: "default" as const,
    flow: "shared Treasury → both pools",
    body: "When both sides act together — a joint venture, a shared water agreement — the Treasury pays into both pools at once. Cooperation is the only direction where everyone's dividend goes up simultaneously, which is exactly the gradient the whole mechanism is trying to point at.",
    viz: (
      <div className="flex items-center justify-center gap-2 text-xs font-bold">
        <span className="rounded-lg bg-accent/70 px-2 py-1.5 text-accent-foreground">Treasury</span>
        <span className="text-primary">→</span>
        <span className="rounded-lg bg-primary/15 px-2 py-1.5 text-primary">pool A +</span>
        <span className="rounded-lg bg-primary/15 px-2 py-1.5 text-primary">pool B +</span>
      </div>
    ),
  },
]

const GUARDRAILS = [
  {
    title: "Per-event cap — ≤5%",
    body: "No single event can move more than the incentive's approved share of the source pool or Treasury, and the protocol hard-caps that share at 5%. One terrible week cannot empty a pool; the response to any event is bounded and known in advance.",
  },
  {
    title: "maxTriggers — a rule retires",
    body: "Every incentive fires a fixed maximum number of times, chosen at proposal time. After the last trigger it goes dormant forever — no rule accumulates open-ended power, and renewing one means passing the dual-majority vote again.",
  },
  {
    title: "Cooldown — no rapid-fire drain",
    body: "After an incentive triggers, a cooldown must pass before it can trigger again. Recurring headlines about the same conflict can't be replayed daily into a rolling confiscation — each firing is a separate, spaced event.",
  },
  {
    title: "patternHash — voters approve a machine",
    body: "The keyword logic ('checkpoint removal' AND 'Jordan Valley') is compiled off-chain to an exact zk-regex circuit, and the proposal commits only its hash. Attestations are accepted only if generated by exactly that circuit — the trigger cannot be reinterpreted, stretched, or lawyered after the vote.",
  },
  {
    title: "Source thresholds — no single newsroom fires it",
    body: "Confirmation needs distinct approved sender domains: at least 1 from community A's press, 1 from B's, and 2 international. A captured outlet, a compromised DKIM key, or one motivated editor can never move money alone — the event must be news everywhere.",
  },
  {
    title: "Reporting window — evidence must cluster",
    body: "All attestations must land within the incentive's reporting window (7 days by default, 10 minutes in this demo) of the first one, and each email's own DKIM-signed date must sit inside that same span. Stale reports and slowly-assembled 'evidence' from different months can't be stitched into one event.",
  },
]

const WORKED_STEPS = [
  { t: "Day 0", body: "The incentive is live: direction positive-for-A, 2% of the Treasury per event, max 3 triggers, 30-day cooldown, pattern committed for (“checkpoint removal” OR “checkpoint dismantled”) AND “Jordan Valley”." },
  { t: "Day 1", body: "The checkpoint comes down. Newsletters go out. A subscriber proves an A-press newsletter matches the committed pattern and attests — the reporting window opens. Source tally: 1 A / 0 B / 0 international." },
  { t: "Day 2", body: "A B-press subscriber attests (1 A / 1 B / 0 intl), then two international wire subscribers attest (1 / 1 / 2). Thresholds met — the event is CONFIRMED and the planned amount is computed: 2% of the 250,000 mUSD Treasury = 5,000." },
  { t: "Day 2–4", body: "The 48-hour dispute window runs. The council (75% supermajority required) finds nothing wrong and does nothing — which is the normal case." },
  { t: "Day 4", body: "Anyone finalizes. The Treasury pays 5,000 at par into community A's pool rewards. With 1,000 verified A members, every member's claimable dividend rises by exactly 5 tokens. Trigger count: 1 of 3; cooldown starts." },
]

export default function EconomicIncentivesPage() {
  return (
    <>
      <section className="container mx-auto px-4 py-14">
        {/* -------------------------------- hero -------------------------------- */}
        <div className="mx-auto max-w-3xl space-y-4 text-center">
          <SectionChip>Incentives, explained</SectionChip>
          <h1 className="font-display text-3xl font-bold tracking-tight sm:text-4xl">
            Pre-agreed prices on war and peace
          </h1>
          <p className="text-muted-foreground md:text-lg">
            An incentive is a standing rule both communities voted for: <em>if this event is proven
            in the news, this much value moves, in this direction.</em> No discretion at trigger
            time, no negotiation under fire — the arguing happens before anything burns, at the
            ballot. Here's where value flows, and the six guardrails that keep any single rule from
            becoming a weapon.
          </p>
          <div className="flex flex-wrap justify-center gap-3 pt-2">
            <Button asChild>
              <Link href="/incentives">Propose &amp; vote — /incentives</Link>
            </Button>
            <Button variant="outline" asChild>
              <Link href="/attest">Attest an event — /attest</Link>
            </Button>
          </div>
        </div>

        {/* ------------------------------ directions ------------------------------ */}
        <div className="mx-auto mt-16 max-w-5xl">
          <SectionHeading
            chip="Three directions"
            title="Where the money comes from decides what the rule means"
            lede="Every incentive declares one of three directions. The direction fixes the source of funds — and that single choice encodes the ethics of the whole mechanism."
          />
          <div className="mx-auto mt-10 grid gap-6 lg:grid-cols-3">
            {DIRECTIONS.map((d) => (
              <div key={d.tag} className="flex flex-col rounded-3xl border-2 border-border bg-card p-6">
                <span className="inline-flex w-fit rounded-full bg-accent/60 px-2.5 py-0.5 text-xs font-semibold text-accent-foreground">
                  {d.tag}
                </span>
                <div className="mt-4 rounded-xl border border-border bg-muted/40 p-3">{d.viz}</div>
                <p className="mt-2 text-center font-mono text-[11px] text-muted-foreground">{d.flow}</p>
                <p className="mt-3 flex-1 text-sm leading-relaxed text-muted-foreground">{d.body}</p>
              </div>
            ))}
          </div>
          <HonestyNote>
            The asymmetry is deliberate: harm is priced against the harming side's own opt-in stake
            (pool → pool), while peace is rewarded from shared money (Treasury → pool). The other
            side's pool is never the source of anyone's reward.
          </HonestyNote>
        </div>

        {/* ------------------------------ guardrails ------------------------------ */}
        <div className="mx-auto mt-20 max-w-5xl">
          <SectionHeading
            chip="Guardrails"
            title="Six limits every rule is born with"
            lede="Each parameter is set at proposal time, frozen on-chain, and approved by both communities as part of the vote. Together they bound the worst case of every incentive before it exists."
          />
          <div className="mx-auto mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
            {GUARDRAILS.map((g) => (
              <div key={g.title} className="rounded-2xl border border-border bg-card p-5">
                <h3 className="font-display text-base font-bold">{g.title}</h3>
                <p className="mt-2 text-sm leading-relaxed text-muted-foreground">{g.body}</p>
              </div>
            ))}
          </div>
        </div>

        {/* ---------------------------- worked example ---------------------------- */}
        <div className="mx-auto mt-20 max-w-5xl">
          <SectionHeading
            chip="Worked example"
            title="The checkpoint-removal incentive, end to end"
            lede="Concrete numbers, protocol-default timing. One de-escalation step becomes a claimable dividend in four days — with every intermediate state visible on-chain."
          />
          <div className="mx-auto mt-10 max-w-3xl space-y-3">
            {WORKED_STEPS.map((s) => (
              <div key={s.t} className="flex gap-4 rounded-2xl border border-border bg-card p-4">
                <span className="w-16 flex-none pt-0.5 font-display text-sm font-bold text-primary">{s.t}</span>
                <p className="text-sm leading-relaxed text-muted-foreground">{s.body}</p>
              </div>
            ))}
          </div>
          <div className="mx-auto mt-8 grid max-w-3xl grid-cols-2 gap-4 sm:grid-cols-4">
            <StatPill label="Treasury before" value="250,000" hint="mUSD" />
            <StatPill label="Event moves" value="5,000" hint="2% of Treasury (≤5% cap)" />
            <StatPill label="A members" value="1,000" hint="verified identities" />
            <StatPill label="Each claims" value="5" hint="tokens — equal per member" tone="positive" />
          </div>
          <HonestyNote>
            Read it like this: nobody decided to pay anyone on day 2 — the payment was decided weeks
            earlier by two majorities, and days 1–4 were just evidence, patience, and arithmetic.
            In this demo the discussion, voting, reporting, and dispute windows all run in 10
            minutes, so you can play the whole timeline in one sitting.
          </HonestyNote>
        </div>

        {/* --------------------------------- CTA --------------------------------- */}
        <div className="mx-auto mt-16 flex max-w-3xl flex-col items-center gap-4 rounded-3xl border-2 border-primary/40 bg-card p-8 text-center">
          <h2 className="font-display text-2xl font-bold">Write a rule, or feed one evidence</h2>
          <p className="text-sm text-muted-foreground">
            Proposing is free and open to anyone; attesting takes one newsletter proof. Both run
            live on Gnosis right now.
          </p>
          <div className="flex flex-wrap justify-center gap-3">
            <Button size="lg" asChild>
              <Link href="/incentives">Propose an incentive — /incentives</Link>
            </Button>
            <Button size="lg" variant="outline" asChild>
              <Link href="/attest">Attest an event — /attest</Link>
            </Button>
          </div>
        </div>
      </section>
    </>
  )
}
