import Link from "next/link"
import { Button } from "@/components/ui/button"
import { SectionChip, SectionHeading, HonestyNote } from "@/components/explainer"

/* The proposer's guide — a step-by-step path from "behavior I want priced"
   to a live incentive that survived a dual-majority vote. */

const STEPS = [
  {
    n: "1",
    title: "Define one behavior, precisely",
    body: "Pick a single event the world's newsrooms would actually report, and phrase it so a stranger could say yes-or-no from a headline: 'military checkpoints removed in the Jordan Valley', not 'meaningful progress on freedom of movement'. Choose its direction honestly — harmful by A or B (priced from that side's pool), positive for A or B (rewarded from the Treasury), or joint (Treasury rewards both). Vague behaviors don't fail at this step; they fail three steps later, at the vote, after wasting everyone's week.",
    tip: "Ask: would both sides' press and two international wires all cover this, with similar words, within a week? If not, narrow it.",
  },
  {
    n: "2",
    title: "Write the keyword logic — it becomes a machine",
    body: "Express your trigger as boolean keyword logic over newsletter text. OR-groups catch phrasing variants; AND-groups pin the event and place. This logic is compiled off-chain into a zk-regex circuit, and your proposal commits only the circuit's hash — the patternHash. From then on, an attestation counts only if it was generated by exactly that circuit. Voters approve the machine, not your prose, so test it first: run the compiled pattern against a personal newsletter archive and check which past editions would have fired it.",
    tip: "Newsletters carry headline-grade language, not full articles — target the words an editor would put in a subject line.",
  },
  {
    n: "3",
    title: "Pick balanced sources — no single newsroom fires it",
    body: "List the newsletter sender domains that count as evidence (e.g. newsletters.reuters.com), each tagged Community A, Community B, or International, and set the distinct-source thresholds — the convention is at least 1 from A's press, 1 from B's, and 2 international. Balance isn't politeness, it's security: an event confirms only when it's news on both sides of the line and beyond it, so one captured outlet or one compromised DKIM key can never move money alone.",
    tip: "Every domain must have its DKIM keys in the on-chain registry — pick established senders, and more than the minimum, so one outlet skipping a story doesn't strand a real event.",
  },
  {
    n: "4",
    title: "Set the caps, count, and cooldown — bound your worst case",
    body: "Three numbers cap what your rule can ever do: the per-event share (redistributionBps, protocol-capped at 5% of the source pool or Treasury), maxTriggers (how many times it can ever fire before retiring), and the cooldown between firings. You also set the reporting window inside which all attestations must cluster (default 7 days, max 30). Voters will read these as your worst case — 2% × 3 triggers = at most 6% of the source, ever. Make that arithmetic easy and unscary.",
    tip: "Modest parameters pass. A rule that could drain 5% × 10 triggers reads as a weapon, and dual majority means the side it's aimed at gets a veto.",
  },
  {
    n: "5",
    title: "Survive discussion, then the dual-majority vote",
    body: "Submission is free, open to anyone, and freezes everything — pattern, sources, thresholds, caps — immutably on-chain; amendments mean a new proposal. Then 7 days of discussion, where people will test your pattern against their archives and hunt for false triggers. Then 3 days of quadratic voting: one ballot per verified identity, n votes lock n² tokens. You need a YES majority among Community A's weight AND among B's, plus 30% joint participation. Pass, and EventAttestation starts accepting proofs against your patternHash. Fail, and you're in a 30-day cooldown before proposing again.",
    tip: "The dual majority is the design doing its job: write a rule the other side can also vote for, or don't bother.",
  },
]

export default function ProposeIncentivePage() {
  return (
    <>
      <section className="container mx-auto px-4 py-14">
        {/* -------------------------------- hero -------------------------------- */}
        <div className="mx-auto max-w-3xl space-y-4 text-center">
          <SectionChip>The proposer's guide</SectionChip>
          <h1 className="font-display text-3xl font-bold tracking-tight sm:text-4xl">
            Write a rule both sides will vote for
          </h1>
          <p className="text-muted-foreground md:text-lg">
            Anyone can propose an incentive — no tokens, no fee, no permission. What stands between
            your idea and a live rule that moves real value is craft: a precise behavior, keyword
            logic that compiles to an honest trigger, balanced sources, bounded parameters, and a
            case persuasive to two majorities at once. Five steps, in order.
          </p>
          <div className="flex flex-wrap justify-center gap-3 pt-2">
            <Button asChild>
              <Link href="/incentives">Propose live — /incentives</Link>
            </Button>
            <Button variant="outline" asChild>
              <Link href="/economic-incentives">How incentives work first</Link>
            </Button>
          </div>
        </div>

        {/* -------------------------------- steps -------------------------------- */}
        <div className="mx-auto mt-14 max-w-3xl space-y-6">
          {STEPS.map((s) => (
            <div key={s.n} className="rounded-3xl border-2 border-border bg-card p-6">
              <div className="flex items-start gap-4">
                <div className="flex h-10 w-10 flex-none items-center justify-center rounded-full bg-primary font-display text-lg font-bold text-primary-foreground">
                  {s.n}
                </div>
                <div>
                  <h3 className="font-display text-lg font-bold">{s.title}</h3>
                  <p className="mt-2 text-sm leading-relaxed text-muted-foreground">{s.body}</p>
                  <p className="mt-3 rounded-xl bg-accent/30 px-3 py-2 text-xs leading-relaxed text-accent-foreground">
                    <strong>Rule of thumb:</strong> {s.tip}
                  </p>
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* ---------------------------- worked example ---------------------------- */}
        <div className="mx-auto mt-20 max-w-5xl">
          <SectionHeading
            chip="Worked example"
            title="The checkpoint-removal trigger, spelled out"
            lede="The classic example from the original concept — keyword logic a compiler can turn into a circuit, and voters can reason about."
          />
          <div className="mx-auto mt-8 max-w-3xl rounded-3xl border-2 border-border bg-card p-6">
            <p className="text-sm text-muted-foreground">
              Behavior: <em>military checkpoints removed in the Jordan Valley</em> — direction
              positive-for-A, rewarded from the Treasury. The committed logic:
            </p>
            <div className="mt-4 rounded-xl bg-muted/60 p-4 font-mono text-sm leading-relaxed">
              (checkpoint removal OR military withdrawal OR IDF dismantles) AND
              <br />
              (Jordan Valley OR West Bank) AND
              <br />
              (removed OR dismantled OR withdrawn OR taken down) AND
              <br />
              (confirmed OR verified OR observed OR documented)
            </div>
            <p className="mt-4 text-sm leading-relaxed text-muted-foreground">
              Read it like this: line 1 names the event, line 2 pins the place, line 3 catches how
              editors phrase completion, line 4 filters speculation ("plans to remove…") from fact.
              OR-groups compile to regex alternations; each AND line becomes a regex that must
              independently match inside the circuit. Sources: haaretz.co.il (A), maannews.net (B),
              reuters.com + apnews.com (international) — thresholds 1 / 1 / 2 within a 7-day window.
              Parameters: 2% of the Treasury per event, max 3 triggers, 30-day cooldown.
            </p>
          </div>
          <HonestyNote>
            Honest limits: keyword triggers inherit the press's blind spots — an event nobody
            newsletter-covers can't fire, and phrasing your pattern didn't anticipate won't match.
            That's why testing against archives, over-including sources, and the human dispute
            window all exist. The pattern is the gate, not the judge.
          </HonestyNote>
        </div>

        {/* --------------------------------- CTA --------------------------------- */}
        <div className="mx-auto mt-16 flex max-w-3xl flex-col items-center gap-4 rounded-3xl border-2 border-primary/40 bg-card p-8 text-center">
          <h2 className="font-display text-2xl font-bold">Ready? The form is live</h2>
          <p className="text-sm text-muted-foreground">
            The propose form at /incentives takes exactly the fields in this guide — direction,
            pattern, tagged sources, thresholds, caps — and submits them to the IncentiveRegistry on
            Gnosis. In this demo, discussion and voting run in 10 minutes each, so you can shepherd
            a proposal from idea to active incentive in one sitting.
          </p>
          <div className="flex flex-wrap justify-center gap-3">
            <Button size="lg" asChild>
              <Link href="/incentives">Open the propose form — /incentives</Link>
            </Button>
            <Button size="lg" variant="outline" asChild>
              <Link href="/governance">How the vote works</Link>
            </Button>
          </div>
        </div>
      </section>
    </>
  )
}
